import { Person, Animal, Car, Bike, Hero } from "./types";

export const people: Person[] = [
  { name: "Janne", age: 17, hobbies: ["skateboarding", "gaming"] },
  { name: "Jolin", age: 18 },
  { name: "Moa", age: 19, hobbies: ["reading", "swimming"] },
  { name: "Alice", age: 25 },
  { name: "Bob", age: 30, hobbies: ["hiking", "cooking"] },
  { name: "Charlie", age: 35 },
  { name: "Diana", age: 28 },
  { name: "Elliot", age: 40, hobbies: ["cycling", "photography"] },
  { name: "Fiona", age: 22 },
  { name: "George", age: 31, hobbies: ["gardening", "painting"] },
  { name: "Hannah", age: 29 },
  { name: "Ian", age: 33, hobbies: ["traveling", "fitness"] },
  { name: "Julia", age: 24 },
  { name: "Kevin", age: 27, hobbies: ["gaming", "writing"] },
  { name: "Laura", age: 32 },
  { name: "Michael", age: 45 },
  { name: "Nina", age: 26 },
  { name: "Oscar", age: 36 },
  { name: "Paula", age: 34, hobbies: ["yoga", "sculpting"] },
  { name: "Quentin", age: 38 },
  { name: "Rebecca", age: 23, hobbies: ["volunteering", "dancing"] },
  { name: "Simon", age: 37 },
  { name: "Tina", age: 41, hobbies: ["reading", "birdwatching", "cycling"] },
  { name: "Uma", age: 30 },
  { name: "Victor", age: 29 },
  { name: "Wendy", age: 25, hobbies: ["running", "knitting"] },
  { name: "Xander", age: 28 },
  { name: "Yasmine", age: 33 },
  { name: "Zach", age: 35, hobbies: ["fishing", "camping", "sewing"] },
  { name: "Angela", age: 42 },
  { name: "Brian", age: 27 },
  { name: "Catherine", age: 40 },
  { name: "David", age: 39, hobbies: ["woodworking", "coding"] },
  { name: "Evelyn", age: 31 },
  { name: "Frank", age: 34 },
  { name: "Grace", age: 26 },
  { name: "Henry", age: 37 },
  { name: "Isabelle", age: 28, hobbies: ["sewing", "drawing"] },
  { name: "Jack", age: 32 },
  { name: "Karen", age: 24 },
  { name: "Liam", age: 35 },
  { name: "Megan", age: 33 },
  { name: "Nathan", age: 29, hobbies: ["reading", "chess"] },
  { name: "Olivia", age: 30 },
  { name: "Patrick", age: 36 },
  { name: "Sophia", age: 27, hobbies: ["surfing", "meditation"] },
];

export const animals: Animal[] = [
  { name: "Elephant", weight: 5400 },
  { name: "Tiger", weight: 310 },
  { name: "Kangaroo", weight: 85 },
  { name: "Penguin", weight: 27 },
  { name: "Eagle", weight: 6.5 },
  { name: "Cheetah", weight: 72 },
  { name: "Dolphin", weight: 300 },
  { name: "Giraffe", weight: 800 },
  { name: "Panda", weight: 100 },
  { name: "Wolf", weight: 45 },
];

export const allowedHobbies = [
  "skateboarding",
  "gaming",
  "reading",
  "swimming",
  "hiking",
  "cooking",
  "cycling",
  "photography",
  "gardening",
  "painting",
  "traveling",
  "fitness",
  "gaming",
  "writing",
  "yoga",
  "sculpting",
  "volunteering",
  "dancing",
  "reading",
  "birdwatching",
  "running",
  "knitting",
  "fishing",
  "camping",
  "woodworking",
  "coding",
  "sewing",
  "drawing",
  "reading",
  "chess",
  "surfing",
  "meditation",
] as const;

export const vehicles: (Car | Bike)[] = [
  {
    brand: "Tesla",
    color: "Red",
    weight: 2000,
    wheels: 4,
    engine: "Electric",
    seats: 5,
    doors: 4,
    description: "",
  },
  {
    brand: "Volvo",
    color: "Black",
    weight: 1800,
    wheels: 4,
    engine: "Diesel",
    seats: 7,
    doors: 5,
    description: "",
  },
  {
    brand: "Giant",
    color: "Blue",
    weight: 12,
    wheels: 2,
    type: "mountain",
    hasBasket: false,
    hasBell: true,
    hasLights: true,
    description: "",
  },
  {
    brand: "Specialized",
    color: "Green",
    weight: 10,
    wheels: 2,
    type: "road",
    hasBasket: false,
    hasBell: false,
    hasLights: true,
    description: "",
  },
  {
    brand: "Canyon",
    color: "Yellow",
    weight: 15,
    wheels: 2,
    type: "electric",
    hasBasket: true,
    hasBell: true,
    hasLights: true,
    description: "",
  },
];

export const heroes: Hero[] = [
  { name: "Arthas", Occupation: "Paladin", level: 45 },
  { name: "Jaina", Occupation: "Mage", level: 50 },
  { name: "Thrall", Occupation: "Shaman", level: 48 },
  { name: "Tyrande", Occupation: "Priest", level: 46 },
  { name: "Illidan", Occupation: "Demon Hunter", level: 55 },
  { name: "Sylvanas", Occupation: "Ranger", level: 52 },
  { name: "Anduin", Occupation: "Priest", level: 40 },
  { name: "Malfurion", Occupation: "Druid", level: 47 },
  { name: "Valeera", Occupation: "Rogue", level: 43 },
  { name: "Kael'thas", Occupation: "Mage", level: 49 },
];

export const allowedOccupations = [
  "",
  "Paladin",
  "Mage",
  "Shaman",
  "Priest",
  "Demon Hunter",
  "Ranger",
  "Druid",
  "Rogue",
] as const;
